markdown: rdiscount
pygments: true
permalink: /post/:title
auto: true
rdiscount:
  extensions: [smart]
exclude: [vendor, .bundle]
name: Sergio Gianazza
url: http://gianu.me
description: The magic trip of a Psychonaut.
twitter: sgianazza
github: gianu
gravatar_url: http://www.gravatar.com/avatar/1eb5eb46d5a4289d3528426b1626c2bb.png
