#!/bin/sh

echo  "Removing legacy _site"
rm -rf _site
echo "Done."

echo "compiling and building site"
export LC_ALL=en_US.UTF8
bundle exec rake compile
bundle exec jekyll build
echo "Done."

echo "copying search.json"
cp -f _site/search.json .
echo "Done."

echo "Adding search.json and js/application.js"
git add search.json js/application.js
echo "done"

echo "Committing and pushing changes"
git commit -m "Automatically add search.json and update js/application.js"
git push origin master
echo "Done! The site is published"
