#!/bin/sh

export LC_ALL=en_US.UTF8
bundle exec rake compile
bundle exec jekyll build

cp _site/search.json .

git add search.json js/application.js
git commit -m "Automatically add search.json and update js/application.js"
git push origin master
